### ISSUE TITLE
Authentication types

### ISSUE THREAD

**Issue by LuizinhoF** [jeansouzak/duf#1]
I was reading through [Authentication.php](https://github.com/jeansouzak/duf/blob/master/src/Prepare/Authentication.php) class and saw that it can only generate Basic auth headers, this severely limits this package usage.

I think it is fine to use it as a default type but DUF should be able to handle custom authentication.

**Comment by jeansouzak** [comment]
You can send an other simple header authentication passing an array with key value, like this:
```
  $header = ["Authorization" => "Basic " . $basicToken];
  //other example
  $header = ["Authorization" => "Bearer " . $bearerToken];
  new WebResource($name, $url, [$allowedSize, $allowedExtensions], $header);
```

**Comment by LuizinhoF** [comment]
It works nicely, thanks.
